### ISSUE TITLE
Example1b do not display identical images

### ISSUE THREAD

**Issue by NicoKiaru** [imglib/imglib2-tutorials#7] opened 2019-03-05 07:47 UTC
![example1b](https://user-images.githubusercontent.com/20223054/53788702-cf3f9780-3f22-11e9-9bca-0e8bbd1a5a4d.png)

As shown in the uploaded image, opening the image in a `ImgMode.CELL` mode displays a skewed image. The 'angle' is 45 degrees, so it's probably related to a single pixel error per line which means a 'length' vs 'length-1' indexation problem of some sort.

**Comment by ctrueden** [comment] 2019-03-05 21:28
If you update pom-scijava to 25.0.0, the issue is fixed.

I am currently bisecting the versions to find out where the fix came in.

**Comment by ctrueden** [comment] 2019-03-05 21:36
Probably the bug was fixed with scifio/scifio@064713feff237deec9a2dd1eb4ba2edcae7f9a6b. I since rewrote the planar bounds logic in SCIFIO more thoroughly; see scifio/scifio@07746ff0d6b5562d59a9baa2d2e3be6eb95dec6c for details.

Anyway, bug is fixed now in this repository. Thanks a lot @NicoKiaru for reporting.

**Closed** 2019-03-05 21:36 UTC
